### ISSUE TITLE
How to `pip install hylaa`?

### ISSUE THREAD

**Issue by maxvonhippel** [stanleybak/hylaa#7]
Hi,
Ideally, I would like to `pip install hylaa` so I can use it globally and not just in the `hylaa` repo on my machine.  Sorry for the n00b question, but how can I do this?  I tried `cd`ing into the repo and doing `pip install .`, but that didn't work.
Thanks!
Max

**Comment by stanleybak** [comment]
We don't have a pip install currently. Do you know if this is easy to do?

For now, just get the source code accessible on your machine and modify `PYTHONPATH` manually and it should work.

**Comment by maxvonhippel** [comment]
I'm not sure how difficult it is.  I'll try to do it, and if I succeed, I'll cut a PR with the changes.

**Comment by maxvonhippel** [comment]
Turns out it's super easy!  I did not try to make this available via any package manager since that's not my place to do (not my package) but my PR makes it locally pip-installable.

If you like this and want to make it available over package managers too I think it's probably fairly easy.

**Comment by maxvonhippel** [comment]
[Here](https://betterscientificsoftware.github.io/python-for-hpc/tutorials/python-pypi-packaging/) is the tutorial I used, which also explains how to make it available on package managers.

**Comment by stanleybak** [comment]
great thanks
